// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: worker_tokens.proto

package web

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWorkerTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateWorkerTokenRequest) Reset() {
	*x = CreateWorkerTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_tokens_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkerTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerTokenRequest) ProtoMessage() {}

func (x *CreateWorkerTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_tokens_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkerTokenRequest) Descriptor() ([]byte, []int) {
	return file_worker_tokens_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorkerTokenRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateWorkerTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Token *WorkerToken `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CreateWorkerTokenResponse) Reset() {
	*x = CreateWorkerTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_tokens_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkerTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerTokenResponse) ProtoMessage() {}

func (x *CreateWorkerTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_tokens_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkerTokenResponse) Descriptor() ([]byte, []int) {
	return file_worker_tokens_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkerTokenResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateWorkerTokenResponse) GetToken() *WorkerToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type ListWorkerTokensRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListWorkerTokensRequest) Reset() {
	*x = ListWorkerTokensRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_tokens_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWorkerTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkerTokensRequest) ProtoMessage() {}

func (x *ListWorkerTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_tokens_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkerTokensRequest.ProtoReflect.Descriptor instead.
func (*ListWorkerTokensRequest) Descriptor() ([]byte, []int) {
	return file_worker_tokens_proto_rawDescGZIP(), []int{2}
}

type ListWorkerTokensResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tokens []*WorkerToken `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *ListWorkerTokensResponse) Reset() {
	*x = ListWorkerTokensResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_tokens_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWorkerTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkerTokensResponse) ProtoMessage() {}

func (x *ListWorkerTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_tokens_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkerTokensResponse.ProtoReflect.Descriptor instead.
func (*ListWorkerTokensResponse) Descriptor() ([]byte, []int) {
	return file_worker_tokens_proto_rawDescGZIP(), []int{3}
}

func (x *ListWorkerTokensResponse) GetTokens() []*WorkerToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type WorkerToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TokenBit    string               `protobuf:"bytes,3,opt,name=token_bit,json=tokenBit,proto3" json:"token_bit,omitempty"`
	CreatedAt   *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt  *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
}

func (x *WorkerToken) Reset() {
	*x = WorkerToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_tokens_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerToken) ProtoMessage() {}

func (x *WorkerToken) ProtoReflect() protoreflect.Message {
	mi := &file_worker_tokens_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerToken.ProtoReflect.Descriptor instead.
func (*WorkerToken) Descriptor() ([]byte, []int) {
	return file_worker_tokens_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkerToken) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkerToken) GetTokenBit() string {
	if x != nil {
		return x.TokenBit
	}
	return ""
}

func (x *WorkerToken) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkerToken) GetLastUsedAt() *timestamp.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type RevokeWorkerTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
}

func (x *RevokeWorkerTokenRequest) Reset() {
	*x = RevokeWorkerTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_tokens_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeWorkerTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeWorkerTokenRequest) ProtoMessage() {}

func (x *RevokeWorkerTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_tokens_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeWorkerTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeWorkerTokenRequest) Descriptor() ([]byte, []int) {
	return file_worker_tokens_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeWorkerTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type RevokeWorkerTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *RevokeWorkerTokenResponse) Reset() {
	*x = RevokeWorkerTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_tokens_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeWorkerTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeWorkerTokenResponse) ProtoMessage() {}

func (x *RevokeWorkerTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_tokens_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeWorkerTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeWorkerTokenResponse) Descriptor() ([]byte, []int) {
	return file_worker_tokens_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeWorkerTokenResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type RevokeAllWorkerTokensRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RevokeAllWorkerTokensRequest) Reset() {
	*x = RevokeAllWorkerTokensRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_tokens_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeAllWorkerTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllWorkerTokensRequest) ProtoMessage() {}

func (x *RevokeAllWorkerTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_tokens_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllWorkerTokensRequest.ProtoReflect.Descriptor instead.
func (*RevokeAllWorkerTokensRequest) Descriptor() ([]byte, []int) {
	return file_worker_tokens_proto_rawDescGZIP(), []int{7}
}

type RevokeAllWorkerTokensResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RevokeAllWorkerTokensResponse) Reset() {
	*x = RevokeAllWorkerTokensResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_tokens_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeAllWorkerTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllWorkerTokensResponse) ProtoMessage() {}

func (x *RevokeAllWorkerTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_tokens_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllWorkerTokensResponse.ProtoReflect.Descriptor instead.
func (*RevokeAllWorkerTokensResponse) Descriptor() ([]byte, []int) {
	return file_worker_tokens_proto_rawDescGZIP(), []int{8}
}

var File_worker_tokens_proto protoreflect.FileDescriptor

var file_worker_tokens_proto_rawDesc = []byte{
	0x0a, 0x13, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6f, 0x64, 0x32, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x18,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x66, 0x0a, 0x19, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x37, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x64, 0x32, 0x5f, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x19, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x55, 0x0a,
	0x18, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x64, 0x32, 0x5f,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x77, 0x65, 0x62,
	0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x06, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x73, 0x22, 0xd5, 0x01, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f,
	0x62, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x42, 0x69, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x3c,
	0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x64, 0x41, 0x74, 0x22, 0x35, 0x0a, 0x18,
	0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x19, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x57, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65,
	0x41, 0x6c, 0x6c, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1f, 0x0a, 0x1d, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65,
	0x41, 0x6c, 0x6c, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xf0, 0x03, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x74, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2e, 0x2e,
	0x6f, 0x64, 0x32, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x68, 0x69, 0x76, 0x65,
	0x2e, 0x77, 0x65, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e,
	0x6f, 0x64, 0x32, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x68, 0x69, 0x76, 0x65,
	0x2e, 0x77, 0x65, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x71,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x73, 0x12, 0x2d, 0x2e, 0x6f, 0x64, 0x32, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2e, 0x2e, 0x6f, 0x64, 0x32, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e,
	0x68, 0x69, 0x76, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x74, 0x0a, 0x11, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2e, 0x2e, 0x6f, 0x64, 0x32, 0x5f, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x52, 0x65,
	0x76, 0x6f, 0x6b, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6f, 0x64, 0x32, 0x5f, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x52, 0x65,
	0x76, 0x6f, 0x6b, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x80, 0x01, 0x0a, 0x15, 0x52, 0x65, 0x76, 0x6f,
	0x6b, 0x65, 0x41, 0x6c, 0x6c, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x73, 0x12, 0x32, 0x2e, 0x6f, 0x64, 0x32, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e,
	0x68, 0x69, 0x76, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x41,
	0x6c, 0x6c, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x6f, 0x64, 0x32, 0x5f, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x2e, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x52, 0x65, 0x76,
	0x6f, 0x6b, 0x65, 0x41, 0x6c, 0x6c, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x6f,
	0x2e, 0x6f, 0x64, 0x32, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x68, 0x69, 0x76,
	0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_worker_tokens_proto_rawDescOnce sync.Once
	file_worker_tokens_proto_rawDescData = file_worker_tokens_proto_rawDesc
)

func file_worker_tokens_proto_rawDescGZIP() []byte {
	file_worker_tokens_proto_rawDescOnce.Do(func() {
		file_worker_tokens_proto_rawDescData = protoimpl.X.CompressGZIP(file_worker_tokens_proto_rawDescData)
	})
	return file_worker_tokens_proto_rawDescData
}

var file_worker_tokens_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_worker_tokens_proto_goTypes = []interface{}{
	(*CreateWorkerTokenRequest)(nil),      // 0: od2_network.hive.web.CreateWorkerTokenRequest
	(*CreateWorkerTokenResponse)(nil),     // 1: od2_network.hive.web.CreateWorkerTokenResponse
	(*ListWorkerTokensRequest)(nil),       // 2: od2_network.hive.web.ListWorkerTokensRequest
	(*ListWorkerTokensResponse)(nil),      // 3: od2_network.hive.web.ListWorkerTokensResponse
	(*WorkerToken)(nil),                   // 4: od2_network.hive.web.WorkerToken
	(*RevokeWorkerTokenRequest)(nil),      // 5: od2_network.hive.web.RevokeWorkerTokenRequest
	(*RevokeWorkerTokenResponse)(nil),     // 6: od2_network.hive.web.RevokeWorkerTokenResponse
	(*RevokeAllWorkerTokensRequest)(nil),  // 7: od2_network.hive.web.RevokeAllWorkerTokensRequest
	(*RevokeAllWorkerTokensResponse)(nil), // 8: od2_network.hive.web.RevokeAllWorkerTokensResponse
	(*timestamp.Timestamp)(nil),           // 9: google.protobuf.Timestamp
}
var file_worker_tokens_proto_depIdxs = []int32{
	4, // 0: od2_network.hive.web.CreateWorkerTokenResponse.token:type_name -> od2_network.hive.web.WorkerToken
	4, // 1: od2_network.hive.web.ListWorkerTokensResponse.tokens:type_name -> od2_network.hive.web.WorkerToken
	9, // 2: od2_network.hive.web.WorkerToken.created_at:type_name -> google.protobuf.Timestamp
	9, // 3: od2_network.hive.web.WorkerToken.last_used_at:type_name -> google.protobuf.Timestamp
	0, // 4: od2_network.hive.web.WorkerTokens.CreateWorkerToken:input_type -> od2_network.hive.web.CreateWorkerTokenRequest
	2, // 5: od2_network.hive.web.WorkerTokens.ListWorkerTokens:input_type -> od2_network.hive.web.ListWorkerTokensRequest
	5, // 6: od2_network.hive.web.WorkerTokens.RevokeWorkerToken:input_type -> od2_network.hive.web.RevokeWorkerTokenRequest
	7, // 7: od2_network.hive.web.WorkerTokens.RevokeAllWorkerTokens:input_type -> od2_network.hive.web.RevokeAllWorkerTokensRequest
	1, // 8: od2_network.hive.web.WorkerTokens.CreateWorkerToken:output_type -> od2_network.hive.web.CreateWorkerTokenResponse
	3, // 9: od2_network.hive.web.WorkerTokens.ListWorkerTokens:output_type -> od2_network.hive.web.ListWorkerTokensResponse
	6, // 10: od2_network.hive.web.WorkerTokens.RevokeWorkerToken:output_type -> od2_network.hive.web.RevokeWorkerTokenResponse
	8, // 11: od2_network.hive.web.WorkerTokens.RevokeAllWorkerTokens:output_type -> od2_network.hive.web.RevokeAllWorkerTokensResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_worker_tokens_proto_init() }
func file_worker_tokens_proto_init() {
	if File_worker_tokens_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_worker_tokens_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkerTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker_tokens_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkerTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker_tokens_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWorkerTokensRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker_tokens_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWorkerTokensResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker_tokens_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker_tokens_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeWorkerTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker_tokens_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeWorkerTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker_tokens_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeAllWorkerTokensRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker_tokens_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeAllWorkerTokensResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_worker_tokens_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_tokens_proto_goTypes,
		DependencyIndexes: file_worker_tokens_proto_depIdxs,
		MessageInfos:      file_worker_tokens_proto_msgTypes,
	}.Build()
	File_worker_tokens_proto = out.File
	file_worker_tokens_proto_rawDesc = nil
	file_worker_tokens_proto_goTypes = nil
	file_worker_tokens_proto_depIdxs = nil
}
